- package.json
cannot install this with react-native 0.5.0
> relax peerDependencies.

- package.json
it's the trend now, among the react native team as well, e.g. see [react-native-linear-gradient](https://github.com/brentvatne/react-native-linear-gradient)
> no peerdeps

- index.js
so hopefully this is good at last!
I have removed the double `convertError` calls
> refactoring index.js

- RNKeychainManager/RNKeychainManager.h
- RNKeychainManager/RNKeychainManager.m
Fixes #49.
Adopts this https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d
> Use absolute references

- README.md
- RNKeychainManager/RNKeychainManager.m
- index.js
Closes #37
Note when testing: this is using ES2016 exports, so make sure to change import statement.
> Shared web credentials support

- README.md
> Add maintainers section to README

- README.md
Add note on proguard exception rule to fix conceal error.
> Update README to include proguard note

- KeychainExample/App.js
Once the form is cleared, it make easier to observe that the credentials are getting loaded from the Keychain system...
> Clear form to better demonstrate "load"

- typings/react-native-keychain.d.ts
Adding the following enums & keys:
- SecAccessControl
- SecAccessible
- LAPolicy
- `accessible` for Options
> Update Typings for Option.accessible and others

- android/build.gradle
> Support React Native 0.56

- android/src/main/java/com/oblador/keychain/KeychainModule.java
Exposes missing method on Android. Fixes #165.
> Export hasInternetCredentialsForServer method in android

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java
Fixes #208 
Remove tryGenerateStrongBoxSecurityKey while there's a better fix like adding an option for this function
> Remove tryGenerateStrongBoxSecurityKey on generateKeyAndStoreUnderAlias

- android/src/main/java/com/oblador/keychain/KeychainModule.java
- android/src/main/java/com/oblador/keychain/PrefsStorage.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorage.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageFacebookConceal.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java
Replace android.support. with androidx.  for AndroidX support
> AndroidX Support

- index.js
- test_index.js
> Flow type fixes

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java
Fixes #208 by simplifying the data decryption implementation. Still not sure why the use of [CipherInputStream](https://developer.android.com/reference/javax/crypto/CipherInputStream) caused the data corruption, but this seems to fix it.
Original decryption implementation seems to be from https://github.com/oblador/react-native-keychain/commit/145a0983cbb3176ea099bee125740badcea027e7, but couldn't find any indication to why the stream based implementation was used originally.
Tested on a Pixel 3a running Android 10
> Fix strongbox decryption data corruption

- KeychainExample/android/build.gradle
- KeychainExample/android/gradle/wrapper/gradle-wrapper.properties
- android/src/test/java/com/oblador/keychain/KeychainModuleTests.java
- build.gradle.kts
Fixed unit tests after library merge:
> Fix biometrics unit tests after merge in master

- README.md
Fixes #303 and applies prettier formatting.
> Fix TOC links in README

- README.md
Add missing `accessControl` to `getGenericPassword`. 
Minor wording changes.
> Add missing prop to `getGenericPassword`

- RNKeychainManager/RNKeychainManager.m
Since write and delete are executed on separate threads (kinda unclear to me why), we enable for some race conditions, for example when one would flood the keychain with writes. By using a single separate queue for all commands we should be able to guarantee order of execution.
> Execute iOS methods on discrete queue

- KeychainExample/android/build.gradle
- android/build.gradle
- build.gradle.kts
This PR is to address the problem that people complain here https://stackoverflow.com/questions/62398553/compilation-failed-android-after-installation-of-react-native-keychain
> Aligned the configuration of the build between all .gradle files

- index.js
- test_index.js
Fixes #482. For more details see that issue :)
> Fix Flow type for Options to work with exact_by_default=true

- src/index.ts
> chore: update docs for accessibility attribute

- KeychainExample/e2e/testCases/storageTypesTest.spec.js
- KeychainExample/src/App.tsx
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageBase.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcb.kt
Closes #403 
Improved key management in CipherStorage by adding checks for key compatibility and regenerating the key if needed.
> fix: setGenericPassword throws "Attempt to invoke virtual method PublicKey()"

- android/src/main/java/com/oblador/keychain/DeviceAvailability.kt
- android/src/main/java/com/oblador/keychain/KeychainModule.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherCache.kt
- ios/RNKeychainManager/RNKeychainManager.m
- src/index.ts
- src/types.ts
This pull request includes several changes to improve the handling of passcode and biometric authentication in the `KeychainModule` for Android and iOS, as well as some code cleanup and refactoring.
> feat: isPasscodeAuthAvailable
