- index.ios.js
When I upgraded to react native 0.7.1 from 0.6.0 I started getting hit by the following warnings:
```
[14:40:52] <END>   transform (321ms)
Unable to resolve module NativeModules from ./node_modules/react-native-keychain/index.ios.js
Unable to resolve module NativeModules from ./node_modules/react-native-keychain/index.ios.js
Unable to resolve module NativeModules from ./node_modules/react-native-keychain/index.ios.js
Unable to resolve module NativeModules from ./node_modules/react-native-keychain/index.ios.js
[14:46:28] <START> find dependencies
```
Using this method of requiring NativeModules fixes it. Thanks!
> Fix NativeModules import

- android/src/main/java/com/oblador/keychain/KeychainModule.java
Fixes crash on Androids with SDK < 19
https://github.com/oblador/react-native-keychain/issues/27
> Use Charset instead of StandardCharset for UTF-8 to support sdk < 19

- README.md
fixes #32 
Let me know if you want it below the Installation or Usage section
> Add a note about iOS 10 keychain sharing entitlement to the README

- RNKeychainManager/RNKeychainManager.m
- android/src/main/java/com/oblador/keychain/KeychainModule.java
- index.js
Every now I then I get reports of `Keychain item not found` for users that should have a keychain item.
I suspect that the default is not good enough and have always previously set `AccessibleAfterFirstUnlock`.
This changes the default so that the keychain item is available when the app is in the background, or even as I suspect, in a transition between background or locked state.
> Fix accessible

- package.json
- typings/react-native-keychain.d.ts
This pull request updates the package.json to use the "types" attribute to declare where the type definition file is located. I am not sure if the "typescript" attribute was an older method of declaring this but I am using TypeScript 2.2.1 and the current type definitions are not found until I use the "types" attribute. See: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html for clarification.
I also updated some of the type definitions to have more accurate promise values.
> Update TypeScript definitions

- android/src/main/java/com/oblador/keychain/KeychainModule.java
this will make it behave same as on ios
> [android] return false instead of exception when entry not present

- README.md
Make installing manual more friendly for beginners
> Fix path for iOS module linking via CocoaPods

- RNKeychain.podspec
- RNKeychain.xcodeproj/project.pbxproj
- RNKeychainManager/RNKeychainManager.m
Now we can use react native keychain on tvOS, I have test it and I use it in my project and it works perfectly
I've disable: 
- setSharedWebCredentialsForServer
- requestSharedWebCredentials
Because they are only for [iOS](https://developer.apple.com/documentation/security/shared_web_credentials)
> Add react-native-keychain on tvOS 

- android/src/main/java/com/oblador/keychain/DeviceAvailability.java
Validate that the build version supports FingerprintManager before using it. Return false when not supported
> Update DeviceAvailability to work with older Android versions

- README.md
- android/src/main/java/com/oblador/keychain/KeychainModule.java
when inserting keychain entry, ios resolves with true, as seen [here](https://github.com/oblador/react-native-keychain/blob/master/RNKeychainManager/RNKeychainManager.m#L220); this makes sure the behavior is the same on android, plus fixing docs
> improve consistency and docs

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java
`NullPointerException` thrown on some Huawei devices is crashing entire app.
Handle all exceptions and rethrow them as caught exceptions.
This is an attempt to prevent issue described in https://github.com/oblador/react-native-keychain/issues/115.
> Catch uncaught exceptions to prevent crash

- android/src/main/java/com/oblador/keychain/KeychainModule.java
`getCurrentActivity` might return `null`, leading to a null pointer exception. Replacing it by `getReactApplicationContext` should work more robustly.
> android: use getReactApplicationContext instead of getCurrentActivity

- android/build.gradle
Hi, as React native 0.56.0 is released with MAJOR android changes such as:
-Gradle 3.5.1
-Compile using Android SDK 26
-Google Maven repo
-etc
more about Change log, specially of Android Here, https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#android-projects-are-now-compiled-using-the-android-26-sdk
and https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#android-specific-changes
Aslo as Per Google new "**Google Play's target API level requirement**", mentioned here  https://developer.android.com/distribute/best-practices/develop/target-sdk
> Google Play will require that new apps target at least Android 8.0 (API level 26) from August 1, 2018, and that app updates target Android 8.0 from November 1, 2018.
It's …
> Update obsolete compile to implementation

- android/src/main/java/com/oblador/keychain/DeviceAvailability.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java
this is a small diff
- as for the null checks - I locally upgraded android gradle plugin and after the upgrade I started getting null warnings. 
- I renamed `isSecure` to `isDeviceSecure` since it's more descriptive. The function is not used anywhere though so we may as well remove it
- added `generateKeyAndStoreUnderAlias ` function. Its body was previously in an if block and it wasn't very clear to me what the block was doing (the `generator.generateKey()` not only returns a `SecterKey` instance, it does other things too, including adding the Alias to Keystore)
> extract a function, add null checks

- README.md
- RNKeychainManager/RNKeychainManager.m
- android/src/main/java/com/oblador/keychain/KeychainModule.java
- index.js
- typings/react-native-keychain.d.ts
This checks if the username/password combination for server is available in the secure storage.
Resolves to `true` if an entry exists or `false` if it doesn't.
> Add hasInternetCredentials

- RNKeychainManager/RNKeychainManager.m
When we create a Core Foundation object, we're responsible for releasing it after we're done with it. `foundTypeRef`, a `CFTypeRef`, was created but not released after use, causing a memory leak. This was fixed by calling `CFRelease(foundTypeRef)` after use.
Fixes #174 
Tested with the KeychainExample app and profiled in Instruments. 
Before changes:
After changes:
> Fix iOS memory leaks

- KeychainExample/App.js
- KeychainExample/android/build.gradle
- README.md
- RNKeychainManager/RNKeychainManager.m
- android/build.gradle
- android/src/main/java/com/oblador/keychain/KeychainModule.java
- android/src/main/java/com/oblador/keychain/SecurityLevel.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorage.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageFacebookConceal.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java
- index.js
**Background**.
Sometimes, we want to make sure that the encryption key that is generated for keychain on Android has a minimum security guarantee. It shouldn't be possible to add items to keychain that might compromise the security.
Also, sometimes we just want to disable certain features if security guarantees are too weak.
We needed that for our application (Status.im), and we thought that that is a good idea to upstream.
I'll be happy for any feedback!
---
**Implementation**
Supported security levels:
- ANY
- SECURE_SOFTWARE
- SECURE_HARDWARE (TEE or SE guarantees).
(1) Add `getSecurityLevel()` API that returns which security level is
supported on this Android version and the specific device.
(2) For APIs that store credentials, an additional optional parameter was added
that fails …
> [Android] Implement security level guarantees.

- typings/react-native-keychain.d.ts
From the documentation:
> Resolves to { username, password } if an entry exists or false if it doesn't.
This fix allows you to have patterns like the following in typescript:
```typescript
const auth = Keychain.getGenericPassword();
if (auth) {
const { username, password } = auth;
> Fix getGenericPassword() type definition

- README.md
After struggling to get this to work between my App and my Share Extension, I think this addition to the README is helpful for others. 
Found out the `service` option is required in that use case.
A question to the maintainers: maybe good to rename `accessGroup` to `appGroupName`? As it is a little confusing because it does not seem to use the "Keychain Access Group" name, which it implies to use if you don't read the README.
> Update README to clarify Keychain Sharing between iOS App and Extension

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java
When a key is not found, in v2.0.0 an error message that "Could not decrypt bytes" would come up. I think in v3 this becomes "Unknown error: Could not decrypt bytes".
This is due to the key being retrieved being null when calling
`cipher.init(Cipher.DECRYPT_MODE, key, ivParams);`, which then fails with an error "java.security.InvalidKeyException: Only SecretKey is supported". So the error messaging around this is really vague and difficult to understand.
This PR adds the exception message in this case to the exception being generated, but for the key not found case another exception is constructed that is easier to understand.
Additionally, while trying to test this I found the module was causing a crash on my API 19 emulator that it could not find a StrongBoxUnavailableException. I'm not …
> Fix a crash on Android 4.x devices, handle key not present error messages better

- index.js
If I understand correctly, `true` should never come back from `getGenericPassword` instead a successful call will resolve with an object while a failure will resolve with `false`. 
`boolean` is approximately equivalent to `true | false`, so we should be able to eliminate the `true` case here.
> Refine flow type for getGenericPassword response

- README.md
Describe how to mock the library so that Jest tests will successfully compile for apps that depend on the library upstream.
> Add a section for how to unbreak Jest test compile

- RNKeychainManager/RNKeychainManager.m
Updates the policy used for `canEvaluatePolicy` to `LAPolicyDeviceOwnerAuthentication` which enables developers to determine the device's `biometryType` even if the permissions are denied or blocked.
> Update getSupportedBiometryType policy

- typings/react-native-keychain.d.ts
Typescript unable to work properly with security levels feature. Adding typings is fixing this issue.
Changes:
* enum with SECURITY_LEVEL options
* add typed return value for getSecurityLevel
* add securityLevel to Options signature
> Add typings for Android Security Levels 

- README.md
Linking is not necessary anymore since React Native 0.60. I've added a note about it in the installation instructions.
> Simplify installation instructions for newer RN

- README.md
Hi,
My application was crashing when a user was trying to call `Keychain.getGenericPassword` on an iPhoneX.
It turned out I needed to add a `NSFaceIDUsageDescription` entry in my `Info.plist` to ask for permission to use FaceID, which was not documented on this project.
I added it in the installation steps as I believe we should be warned about this during installation.
> Document required FaceID permission for iOS

- .npmignore
- package.json
A quick update to `.npmignore` and the `files` section in `package.json` that reduces the distribution artifact size by more than 70% (mainly by no longer including Gradle wrapper, which is not used by app consumers).
Before:
```
npm notice name:          react-native-keychain
npm notice version:       4.0.0
npm notice filename:      react-native-keychain-4.0.0.tgz
npm notice package size:  79.7 kB
npm notice unpacked size: 172.2 kB
npm notice total files:   31
```
After:
```
npm notice name:          react-native-keychain
npm notice version:       4.0.0
npm notice filename:      react-native-keychain-4.0.0.tgz
npm notice package size:  22.9 kB
npm notice unpacked size: 103.8 kB
npm notice total files:   22
```
CC @SaeedZhiany
> Update npmignore and files package

- typings/react-native-keychain.d.ts
Fixes an incorrect TypeScript type reference (`LAPolicy` doesn't exist and should be `AUTHENTICATION_TYPE`)
> Fix TS typing (LAPolicy -> AUTHENTICATION_TYPE)

- README.md
- RNKeychainManager/RNKeychainManager.m
Great news! I'm successfully using this package in my Catalyst project.
However, the [`SecRequestSharedWebCredential`](https://developer.apple.com/documentation/security/1617896-secrequestsharedwebcredential
) and `SecAddSharedWebCredential` functions are not supported in Catalyst, so the corresponding wrapper methods need to be conditionally excluded.
> Support macOS Catalyst

- typings/react-native-keychain.d.ts
The TypeScript type definition for `getInternetCredentials` states that it would always return a promise for an object containing `username` and `password`. The [documentation](https://github.com/oblador/react-native-keychain#getinternetcredentialsserver--authenticationprompt-) on the other hand states that it can also return a promise for `false` in case the key is not found in the storage.
Looking at the source code for [iOS](https://github.com/oblador/react-native-keychain/blob/569a408317eb0c0ad6ac1fb46fb82e5b0af59ee0/RNKeychainManager/RNKeychainManager.m#L332) and [Android](https://github.com/oblador/react-native-keychain/blob/653140d27fadf8d9a9c397e44a807f4ccb852003/android/src/main/java/com/oblador/keychain/KeychainModule.java#L109), it seems that the documentation is correct while …
> Fix return types for getInternetCredentials

- typings/react-native-keychain.d.ts
Currently, getSupportedBiometryType returns generic string, but the enumeration of biometrics type is predefined.
This PR adds BIOMETRIC_TYPE enum to typings and modifies getSupportedBiometryType so it returns value from the enum.
> Add BIOMETRY_TYPE enum

- README.md
Add more clarity to when it returns `null`. 
Got stuck, when I was assuming this lib is broken, on android device with fingerprint reader, but not enrolled in Fingerprint.
> Add more details to getSupportedBiometryType()

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java
currently, if validateKeySecurityLevel fails on key generation, the key remains in the keystore, and a subsequent add for that same key will succeed due to this check:
https://github.com/oblador/react-native-keychain/blob/5f5c651f9978bfe134914e02113d0ea4f9cd9331/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java#L97
> fix: remove key if failed to generate with sufficient security level

- README.md
Removes a notice under `getSupportedBiometryType` that is no longer valid after a recent API change (https://github.com/oblador/react-native-keychain/pull/240) . This method always returns the biometry type, if the device supports it. It only returns `null` if the device doesn't support any of the biometry types.
> Update getSupportedBiometryType docs

- android/src/main/java/com/oblador/keychain/KeychainModule.java
As described in #305, failing the whole flow in the `onAuthenticationFailed` callback seems incorrect.
The BiometricPrompt stays open if your fingerprint is not recognized for some reason (a common occurence), but fails to complete after matching.
This PR disables onAuthenticationFailed entirely.
> Don't fail authentication flow onAuthenticationFailed

- index.js
this is not documented in readme, but codebases still rely on this; we should warn them they should use what is documented
> deprecate service string

- KeychainExample/App.js
- README.md
- android/src/main/java/com/oblador/keychain/KeychainModule.java
**PR Description**
The default behaviour for `setGenericPassword` is different for iOS vs Android in v5.0.0 of this library. This PR aims to fix that.
**Details**
In v4.0.5 of `react-native-keychain` the default implementation allows users to set and get generic passwords in both iOS and Android without having to authenticate themselves. By passing `options` it is possible to modify this default behaviour.
In v5.0.0 the above still holds true for iOS. However, the default behaviour changed on Android devices that support biometrics. Such devices will prompt users to authenticate themselves even when passwords are stored without passing an `accessControl` value as an option, since they use the best available secured storage by default when setting passwords.
**Fix**
This PR restores the …
> Restore default behaviour for setGenericPassword on Android

- .flowconfig
- index.js
- package.json
- yarn.lock
Flow 0.107 is the latest version compatible with React Native 0.61. This PR fixes errors that surface with this version compared to currently used 0.105, by introducing a workaround, since the code that fails is only temporary. It's tricky to type objects that transform to other objects, and unfortunately I don't have enough time to fix it properly. That's why I believe this "fix" is sufficient. 
FYI, React Native 0.62 bumps Flow to 0.113, while still being compatible with 0.116. This library is currently not compatible with 0.116, including having this fix. However, removing code responsible for normalizing config would fix that. My suggestion – remove deprecated APIs (`service` as a string and `authenticationPrompt` as a string) when migrating to React Native 0.62 and bumping major …
> fix: workaround for type errors from Flow 0.107

- README.md
- android/build.gradle
- android/src/main/java/com/oblador/keychain/DeviceAvailability.java
- android/src/main/java/com/oblador/keychain/KeychainModule.java
- index.js
- typings/react-native-keychain.d.ts
This PR extends the existing enums and native android code to be able to identify the biometry type enrolled on the device.
Previously the library assumed that it was always Fingerprint, but that's not always the case, e.g. on a Pixel 4, which has no fingerprint sensor.
> Add face and iris recognition identification - Android

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageBase.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAesCbc.java
A PR (https://github.com/oblador/react-native-keychain/pull/288) a while back was merged to fix an issue where decrypting the keychain using a `CipherInputStream` causes certain Google Pixel devices to throw an exception and hang.
The change seems to have been inadvertently reverted in the large refactoring that took place in https://github.com/oblador/react-native-keychain/pull/260.
This PR reintroduces that fix.
> Reintroduce a fix for strongbox decryption data corruption (#383)

- RNKeychain.podspec
Latest Xcode 12 fails to build without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
> fix: Xcode 12 compatibility

- RNKeychainManager/RNKeychainManager.m
Removing the `LocalLAuthentication` check lets us buid for tvOS with `react-native-tvos`
Co-authored-by: @gaborkajtar
> [tvOS] remove LAPolicy to fix build

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcb.java
Increase `UserAuthenticationValidityDurationSeconds` in `CipherStorageKeychainRsaEcb.java` to 5 seconds as suggested in this comment: https://github.com/oblador/react-native-keychain/issues/318#issuecomment-607346478
I was experiencing the same `UserNotAuthenticatedException` on a Samsung S7 (Android 7.0), and making this change fixed this issue.
> Increase UserAuthenticationValidityDuration to fix UserNotAuthenticatedException

- RNKeychainManager/RNKeychainManager.m
For old devices with no TouchID or FaceID calling the getSupportedBiometryType() returns TouchID. Added one more check to rectify the issue.
> fix issue in iOS devices with no Biometric hardware returning TouchID

- index.js
This PR addresses the issue in https://github.com/oblador/react-native-keychain/issues/388
It changes three lines in index.js to more safely handle the setting of the `.SECURITY_LEVEL` field for `RNKeychainManager`. This addresses issue that arise when other repos use `react-native-keychain` as a dependency, such as `react-native-pincode`
This PR addresses the error `null is not an object (evaluating 'RNKeychainManager.SECURITY_LEVEL_ANY')` as discussed in the issue above.
> RNKeychainManager set SECURITY_LEVEL safely (Addressing Issue #388)

- android/src/main/java/com/oblador/keychain/KeychainModule.java
**Overview**
This fixes the issue where Android passive (face / iris) biometrics can 'timeout' on the KeyStore unlock between a successful biometric scan and the user selecting the 'Confirm' button.
This issue is seen under issue #318. Under that issue I left a comment here https://github.com/oblador/react-native-keychain/issues/318#issuecomment-735647434
**The Problem**
On Android (using RSA) and when using passive (face / iris) biometrics, the `setUserAuthenticationValidityDurationSeconds` countdown starts as soon as the user successfully completes the biometric face scan. If the user does not press the 'Confirm' button on the Android popup within the set number of seconds in that method (currently set to `5` as of the date of this PR) then the KeyStore is locked again. Once the user …
> Fix Android KeyStore unlock timeouts when using passive biometrics by setting a confirmation step bypass

- android/src/main/java/com/oblador/keychain/KeychainModule.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorage.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageFacebookConceal.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAesCbc.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcb.java
- android/src/main/java/com/oblador/keychain/decryptionHandler/DecryptionResultHandler.java
- android/src/main/java/com/oblador/keychain/decryptionHandler/DecryptionResultHandlerInteractiveBiometric.java
- android/src/main/java/com/oblador/keychain/decryptionHandler/DecryptionResultHandlerInteractiveBiometricManualRetry.java
- android/src/main/java/com/oblador/keychain/decryptionHandler/DecryptionResultHandlerNonInteractive.java
- android/src/main/java/com/oblador/keychain/decryptionHandler/DecryptionResultHandlerProvider.java
- android/src/test/java/com/oblador/keychain/KeychainModuleTests.java
- android/src/test/java/com/oblador/keychain/decryptionHandler/DecryptionResultHandlerInteractiveBiometricManualRetryTest.java
- android/src/test/java/com/oblador/keychain/decryptionHandler/DecryptionResultHandlerInteractiveBiometricTest.java
- android/src/test/java/com/oblador/keychain/decryptionHandler/DecryptionResultHandlerProviderTest.java
- build.gradle.kts
Fixes #446 
Fixes #335 
This change addresses the issue with biometric retry on OnePlus devices. The main approach is taken from the incredible investigation done by the user in [this forum post](https://forums.oneplus.com/threads/oneplus-7-pro-fingerprint-biometricprompt-does-not-show.1035821/#post-21710422).
The idea is to call `BiometricPrompt.cancelAuthentication()` after each `onAuthenticationFailed` received. After manual cleanup, the biometric auth is retried (without creating a new `waitForResult` block). When the user runs out of retries the flow completes gradually in `onAuthenticationError` which throws `CryptoFailedException`.
I verified this solution on my OnePlus 6T running OxygenOS 10.
**TODO**
> Fix biometric retry on OnePlus devices

- RNKeychainManager/RNKeychainManager.m
This issue can be found only on iOS, android works as expected.
It seems like `authenticationPrompt` option is only working for `getGenericPassword`, contrary to the docs in README.md. 
This fix allows the use of the  `authenticationPrompt` option for `getInternetCredentialsForServer`
There is also an issue opened for this two years ago: https://github.com/oblador/react-native-keychain/issues/201
*Testing*
The following snippet should add a description text to the biometrics prompt
```
import Keychain from "react-native-keychain";
Keychain.setInternetCredentials('server', 'user', 'pass', {
accessControl: Keychain.ACCESS_CONTROL.BIOMETRY_ANY
}).then(async () => {
await Keychain.getInternetCredentials('server', {
authenticationPrompt: {
title: 'Place your finger on the home button to …
```
> use authenticationPrompt in getInternetCredentialsForServer

- README.md
- android/src/main/java/com/oblador/keychain/KeychainModule.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageBase.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageFacebookConceal.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAesCbc.java
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcb.java
- android/src/test/java/com/oblador/keychain/KeychainModuleTests.java
This is a set of changes to Android native component to optimise speed. 
The main reason for slowness is that RSA is a very cpu intensive algorithm. The changes in this PR try to mitigate this by removing unneeded calls and I've also added a less secure (and thereby much faster) encryption option, to be used for testing if the cipher works on the device. 
General policy changes is that the option to upgrade ciphers now defaults to false. And upgrades will only happen for keys stored with FacebookConseal cipher.
**KeychainModule.java - _getGenericPassword_**
We no longer always check for available ciphers on the device when getting a password. We instead only do this test if we should upgrade ciphers. 
**CipherStorageKeystoreRsaEcb.java**
Adding an alternative key size to use for testing …
> Speed optimisations for Android

- index.js
Removed async from getAllGenericPasswordServices to fix 
```
ERROR  Could not get all keys. TypeError: ReactNativeKeychain.getAllGenericPasswordServices is not a function. (In 'ReactNativeKeychain.getAllGenericPasswordServices()', 'ReactNativeKeychain.getAllGenericPasswordServices' is undefined)
```
> Update index.js fix getAllGenericPasswordServices undefined error

- KeychainExample/README.md
- KeychainExample/macos/.gitignore
- KeychainExample/macos/KeychainExample-macOS/AppDelegate.h
- KeychainExample/macos/KeychainExample-macOS/AppDelegate.m
- KeychainExample/macos/KeychainExample-macOS/Assets.xcassets/AppIcon.appiconset/Contents.json
- KeychainExample/macos/KeychainExample-macOS/Assets.xcassets/Contents.json
- KeychainExample/macos/KeychainExample-macOS/Base.lproj/Main.storyboard
- KeychainExample/macos/KeychainExample-macOS/Info.plist
- KeychainExample/macos/KeychainExample-macOS/KeychainExample.entitlements
- KeychainExample/macos/KeychainExample-macOS/ViewController.h
- KeychainExample/macos/KeychainExample-macOS/ViewController.m
- KeychainExample/macos/KeychainExample-macOS/main.m
- KeychainExample/macos/KeychainExample.xcodeproj/project.pbxproj
- KeychainExample/macos/KeychainExample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- KeychainExample/macos/KeychainExample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- KeychainExample/macos/KeychainExample.xcodeproj/xcshareddata/xcschemes/KeychainExample-macOS.xcscheme
- KeychainExample/macos/KeychainExample.xcworkspace/contents.xcworkspacedata
- KeychainExample/macos/KeychainExample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- KeychainExample/macos/Podfile
- KeychainExample/macos/Podfile.lock
- KeychainExample/package.json
- KeychainExample/yarn.lock
- RNKeychain.podspec
- RNKeychain.xcodeproj/project.pbxproj
- RNKeychainManager/RNKeychainManager.m
Hi! We've been using `react-native-keychain` lib to develop our mobile app. However, recently we had to port our app to macOS, so as part of this process, we added support of macOS to this lib as well. It was pretty straightforward to do, so I decided to give back to the community results of our work. I hope you will find this feature useful, and thanks for a great product!
- Added dummy macOS example (see attached gif)
- removed unneeded import of `<UIKit/UIKit.h>` (it's not needed even for iOS)
> Added support for macos

- android/build.gradle
- android/src/test/java/com/oblador/keychain/MocksForProvider.java
- android/src/test/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAesCbcTests.java
- android/src/test/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcbTests.java
Starting from JDK 11 there are more nullability checks inside the GetInstance methods of javax.crypto package.
This causes the native tests to fail. This is being fixed by mocking the result of `getAlgorithm` method on the keys.
- Bump all test dependencies to the latest
- Replace `when/doReturn` with `doReturn/when` to fix debugging tests in AS
> Fix android native tests

- react-native.config.js
CLI version 8 introduced large changes to autolinking https://github.com/react-native-community/cli/pull/1537 which breaks this library, due to a redundant podspec configuration. It's not needed, so removing it fixes it while retaining backwards support.
> Fix autolinking in React Native 0.69

- RNKeychainManager/RNKeychainManager.m
Hey.
This PR makes sure that iOS-style keychain is used for the macOS target. The reason for this is it allows portability between iOS and macOS apps.
This is considered to be good practice according to Apple, there's some more info about it here: https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain
> macos: Use iOS-style keychain

- README.md
- RNKeychainManager/RNKeychainManager.m
- index.js
- typings/react-native-keychain.d.ts
This has been deprecated since iOS 13
https://developer.apple.com/documentation/security/ksecattraccessiblealwaysthisdeviceonly?language=objc
Apple docs currently mention: `This is not recommended for application use`
> Remove deprecated kSecAttrAccessibleAlwaysThisDeviceOnly

- RNKeychainManager/RNKeychainManager.m
'kSecUseDataProtectionKeychain' is only available on iOS 13.0 or newer
Enclose 'kSecUseDataProtectionKeychain' in an @available check to silence this warning
Probable Cause https://github.com/oblador/react-native-keychain/pull/536
> ios 13 check

- gradle.properties
As the project is migrated to AndroidX and robolectric is [updated](https://github.com/oblador/react-native-keychain/commit/6963bfd6c1e4e70b23c02f54e319523b62077aef#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aL82) to 4.7.3 (which include one more [migration](https://github.com/robolectric/robolectric/pull/5525) to androidx), we should be safe by disabling `jetifier` on Android, which removes additional build steps and potentially saves build time.
The flag is [false](https://developer.android.com/jetpack/androidx#using_androidx_libraries_in_your_project) by default if it is not specified.
> Disable Android Jetifier

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcb.java
Fix for Android >= 11 to force the use of biometry if required : an attacker could bypass the use of biometry by unlocking the device with the pin and then could access the keychain, even though we would like it to be protected with the biometry.
Fix coming from a comment on this PR : https://github.com/oblador/react-native-keychain/pull/592
It should solve for Android >=11 the issues : 
- https://github.com/oblador/react-native-keychain/issues/593
- https://github.com/oblador/react-native-keychain/issues/518
However, it does not solve the issue for Android < 11 due to the way the keychain is implemented on Android.
> use setUserAuthenticationParameters for android >= 11

- android/build.gradle
The following lines of code were added to android's build.gradle.
```
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
```
What this fixes:
* Older react native projects not handling lambda functions.
Error Message:
```
error: method references are not supported in -source 7
final Thread warmingUp = new Thread(instance::internalWarmingBestCipher, "keychain-warming-up");
^
(use -source 8 or higher to enable method references)
```
> [Fix][Android] Bugfix for lambda functions not workin in older projects.

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcb.java
Upon app startup, I'm noticing this error showing up
```
11-13 19:16:28.052   711   711 E android.hardware.keymaster@4.1-service.citadel: GenerateKey : device response error code: UNSUPPORTED_KEY_SIZE
11-13 19:16:28.052   749   779 E keystore2: keystore2::error: In generate_key.
11-13 19:16:28.052   749   779 E keystore2:
11-13 19:16:28.052   749   779 E keystore2: Caused by:
11-13 19:16:28.052   749   779 E keystore2:     0: While generating Key without explicit attestation key.
11-13 19:16:28.052   749   779 E keystore2:     1: Error::Km(ErrorCode(-6))
11-13 19:16:28.059 27168 27303 W CipherStorageBase: StrongBox security storage is not available.
11-13 19:16:28.059 27168 27303 W CipherStorageBase: java.security.ProviderException: Failed to generate key pair.
11-13 19:16:28.059 27168 …
```
> [Fix][Android] Unsupported RSA key size for StrongBox

- README.md
- RNKeychain.podspec
- RNKeychainManager/RNKeychainManager.m
- typings/react-native-keychain.d.ts
This PR adds support for [React Native visionOS](https://github.com/callstack/react-native-visionos), the new out-of-tree platform.
Vision OS has the new Optic ID biometric, but it behaves same as on iOS. All APIs used here are supported, so it was just a matter of considering `TARGET_OS_VISION` in the same preprocessor directives that already had `TARGET_OS_IOS`.
If you think this is good, I can update the docs with visionOS support in a next commit :)
> feat: add visionOS support

- RNKeychainManager/RNKeychainManager.m
Fixes #624 
Remove `@available(visionOS 1, *)`, which is only available on Xcode 15 and above. Use obj-c preprocessor directives instead.
This was following the same approach as iOS in the lines below `@available(iOS 11, *)`. iOS needs this because FaceID is only available on iOS 11 and above. VisionOS does not need it because visionOS 1 already has OpticID since launch.
Tested on Xcode 14.3.1 and 15.2.
> fix: unrecognized platform name visionOS

- README.md
It seems Travis is no more in use:
Since it was linking the test CI:
https://github.com/oblador/react-native-keychain/pull/97/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485
I updated the badge with the related GHA badge.
> chore(docs): fix test badge

- android/build.gradle
- android/gradle.properties
- android/react-native-helpers.gradle
- yarn.lock
> fix: resolve build issues with React Native 0.69-0.71

- .github/workflows/e2e_tests.yaml
- .github/workflows/gradle_build.yaml
- android/build.gradle
- android/gradle.properties
- android/src/main/AndroidManifest.xml
- android/src/main/java/com/oblador/keychain/KeychainModule.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageBase.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageFacebookConceal.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAesCbc.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreRsaEcb.kt
Closes #630
This pull request improves StrongBox detection on Android devices. It addresses issues with the existing implementation and ensures more reliable identification of StrongBox support.
Extra: A new Gradle build workflow has been introduced for continuous integration. This automates the build process and helps ensure code quality and stability.
> fix: improve strongbox detection

- android/src/main/java/com/oblador/keychain/KeychainModule.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAesGcm.kt
- src/index.ts
- src/normalizeOptions.ts
- src/types.ts
After introducing the AES_GCM cipherStorage, setGenericOptions for AES_GCM with biometrics now also requires an authenticationPrompt.
> fix: authenticationPrompt for SetOptions

- src/index.ts
If no options is passed to setInternetCredentials it will throw an error.
> setInternetCredentials default value for authenticationPrompt

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageBase.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAesGcm.kt
This fixes the javax.crypto.IllegalBlockSizeException that sometimes occurs during decryption.
```
javax.crypto.IllegalBlockSizeException
java.io.IOException: javax.crypto.IllegalBlockSizeException
at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:133)
at javax.crypto.CipherInputStream.read(CipherInputStream.java:249)
at javax.crypto.CipherInputStream.read(CipherInputStream.java:225)
```
> fix: IllegalBlockSizeException on Android while decrypting

- KeychainExample/e2e/utils/matchLoadInfo.ts
- android/src/main/java/com/oblador/keychain/KeychainModule.kt
> fix: parallel set and get operations

- android/src/main/java/com/oblador/keychain/KeychainModule.kt
This pull request replaces the experimental limitedParallelism with a mutex mechanism to manage concurrency in the project.
> chore: use mutex instead of experimental limitedParallelism

- package.json
Updated the node engine to >= 16 to make it compatible with Node 16 runtime and to skip using `yarn install --ignore-engines` for node version less than 18
> fix: update node engine to >=16

- android/react-native-helpers.gradle
Update the React Native package resolution in Android for monorepos, aligning with the recent approach used in [`react-native-reanimated`](https://github.com/software-mansion/react-native-reanimated/blob/b703185e9f3ea3dfd5247477177820795c6f23ec/packages/react-native-reanimated/android/build.gradle#L73-L88).
This update introduces a nesting-agnostic resolution approach, making it more adaptable to various monorepo structures. Different projects organize their repositories with varying levels of nesting. For example, in the [`@divvy/mobile`](https://github.com/divvixyz/divvi-mobile) framework, apps are structured within the `/apps` directory rather than at the root. This change ensures better compatibility across different monorepos.
> fix: update Android `react-native` resolution approach in monorepos

- src/normalizeOptions.ts
the warning message in `normalizeServerOption` says to use
```
{ service: serverOrOptions }
```
but this normalize code handles the `server` options, not the `service` option.
Fixes that typo to make it correct
> fix: typo in serverOrOptions

- KeychainExample/src/App.tsx
1. Moved tab styles from inline to StyleSheet
2. Added tab text styles
Prevents github linter warning
> fix: Example App - linter: react-native/no-inline-styles

- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageBase.kt
Improves error handling for cryptographic operations by adding specific handling for `AEADBadTagException`. This exception occurs during AES-GCM decryption when the authentication tag verification fails, indicating possible data corruption or tampering.
currently unhandled: https://github.com/oblador/react-native-keychain/issues/730
- Added explicit handling for `javax.crypto.AEADBadTagException` in `CipherStorageBase`
- Improved error message to better describe the cause and potential solutions
- Added `CryptoFailedException` to `@Throws` annotation 
Previous generic error handling is now replaced with a specific message for authentication failures:
"Decryption failed: Authentication tag verification failed. This usually indicates that the encrypted data was modified, corrupted, or is …
> fix: add error handling in decryptBytes to throw CryptoFailedException for AEADBadTagException

- android/src/main/java/com/oblador/keychain/KeychainModule.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherCache.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageBase.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAesGcm.kt
This PR improves the management of `Cipher` instances by implementing a new `CipherCache` utility with ThreadLocal-based caching. These changes enhance thread safety, and might help mitigate potential causes of [AEADBadTagException](https://github.com/oblador/react-native-keychain/issues/730). By eliminating shared mutable state, ensuring proper reinitialisation, and cleaning up cached resources, the PR addresses issues such as state leakage that can lead to authentication tag mismatches.
- **New CipherCache Utility:**
- Implemented a new `CipherCache` singleton with ThreadLocal storage to manage `Cipher` instances.
- Ciphers are cached per transformation string to support different configurations.
- **Thread-Safe Caching:**
- Replaced the old single-instance caching mechanism in …
> refactor: Improve Cipher Management with Thread-Safe Caching

- KeychainExample/e2e/testCases/accessControlTest.spec.js
- KeychainExample/e2e/testCases/storageTypesTest.spec.js
- KeychainExample/e2e/utils/authHelpers.js
- KeychainExample/e2e/utils/matchLoadInfo.ts
**Introducing helper functions:**
- waitForAuthValidity to wait for the authentication period to expire.
- enterBiometrics to simulate biometric interaction on Android.
- enterPasscode to simulate passcode entry on Android.
Adding a small buffer to the wait period for reliable test execution.
also corrected typo in file name
> test: e2e - add helpers for entering passcode / biometrics

- android/src/main/java/com/oblador/keychain/DeviceAvailability.kt
- android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageBase.kt
Increase the sdk level requirement for strongbox usage from android 9 to android 12 in order to improve performance of low-end devices with old android versions. 
Attestation level drops from STRONGBOX to TRUSTED_ENVIRONMENT on devices where a TEE exists. Keys are still hardware-backed inside TrustZone; risk increase is limited to sophisticated physical side-channel attacks.
From Google docs https://developer.android.com/privacy-and-security/keystore
> Increase min sdk requirement for strongbox
